alemi/alemi/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r'^users/', include('bootcamp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Third party apps here
    url(r'^comments/', include('django_comments.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^markdownx/', include('markdownx.urls')),
    # Local apps here
    url(r'^notifications/',
        include('bootcamp.notifications.urls', namespace='notifications')),
    url(r'^articles/',
        include('bootcamp.articles.urls', namespace='articles')),
    url(r'^news/', include('bootcamp.news.urls', namespace='news')),
    url(r'^messages/',
        include('bootcamp.messager.urls', namespace='messager')),
    url(r'^qa/', include('bootcamp.qa.urls', namespace='qa')),
    url(r'^search/', include('bootcamp.search.urls', namespace='search')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

alemi/articles/urls.py
from django.urls import path

from .views import (ArticlesListView, DraftsListView,
                                     CreateArticleView, EditArticleView,
                                     DetailArticleView)
app_name = 'articles'
urlpatterns = [
    path('', ArticlesListView.as_view(), name='list'),
    path('write-new-article/', CreateArticleView.as_view(), name='write_new'),
    path('drafts/', DraftsListView.as_view(), name='drafts'),
    path('edit/<int:pk>/', EditArticleView.as_view(), name='edit_article'),
    path('<slug:slug/', DetailArticleView.as_view(), name='article'),
]

alemi/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = 'qa'
urlpatterns = [
    url(r'^$', views.QuestionListView.as_view(), name='index_noans'),
    url(r'^answered/$', views.QuestionAnsListView.as_view(), name='index_ans'),
    url(r'^indexed/$', views.QuestionsIndexListView.as_view(), name='index_all'),
    url(r'^question-detail/(?P<pk>\d+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^ask-question/$', views.CreateQuestionView.as_view(), name='ask_question'),
    url(r'^propose-answer/(?P<question_id>\d+)/$', views.CreateAnswerView.as_view(), name='propose_answer'),
    url(r'^question/vote/$', views.question_vote, name='question_vote'),
    url(r'^answer/vote/$', views.answer_vote, name='answer_vote'),
    url(r'^accept-answer/$', views.accept_answer, name='accept_answer'),
]

alemi/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

alemi/articles/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count
from django.utils.translation import ugettext_lazy as _

from slugify import slugify

from django_comments.signals import comment_was_posted
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from taggit.managers import TaggableManager


# from bootcamp.notifications.models import Notification, notification_handler


class ArticleQuerySet(models.query.QuerySet):
    """Personalized queryset created to improve model usability"""

    def get_published(self):
        """Returns only the published items in the current queryset."""
        return self.filter(status="P")

    def get_drafts(self):
        """Returns only the items marked as DRAFT in the current queryset."""
        return self.filter(status="D")

    # def get_counted_tags(self):
    #     tag_dict = {}
    #     query = self.filter(status='P').annotate(
    #         tagged=Count('tags')).filter(tags__gt=0)
    #     for obj in query:
    #         for tag in obj.tags.names():
    #             if tag not in tag_dict:
    #                 tag_dict[tag] = 1
    #
    #             else:  # pragma: no cover
    #                 tag_dict[tag] += 1
    #
    #     return tag_dict.items()


class Article(models.Model):
    DRAFT = "D"
    PUBLISHED = "P"
    STATUS = (
        (DRAFT, _("Draft")),
        (PUBLISHED, _("Published")),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, related_name="author",
        on_delete=models.SET_NULL)
    image = models.ImageField(
        _('Featured image'), upload_to='articles_pictures/%Y/%m/%d/')
    timestamp = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, null=False, unique=True)
    slug = models.SlugField(max_length=80, null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    content = MarkdownxField()
    edited = models.BooleanField(default=False)
    # tags = TaggableManager()
    objects = ArticleQuerySet.as_manager()

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ("-timestamp",)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.user.username}-{self.title}",
                                to_lower=True, max_length=80)

        super().save(*args, **kwargs)

    def get_markdown(self):
        return markdownify(self.content)


# def notify_comment(**kwargs):
#     """Handler to be fired up upon comments signal to notify the author of a
#     given article."""
#     actor = kwargs['request'].user
#     receiver = kwargs['comment'].content_object.user
#     obj = kwargs['comment'].content_object
#     notification_handler(
#         actor, receiver, Notification.COMMENTED, action_object=obj
#         )
#
#
# comment_was_posted.connect(receiver=notify_comment)

alemi/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from .models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(
        widget=forms.HiddenInput(), required=False, initial=False)
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ["title", "content", "image", "status", "edited"]

alemi/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# from bootcamp.helpers import AuthorRequiredMixin
from .models import Article
from .forms import ArticleForm


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""
    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""
    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Your article has been created.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class EditArticleView(LoginRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""
    model = Article
    message = _("Your article has been updated.")
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, DetailView):
    """Basic DetailView implementation to call an individual article."""
    model = Article

alemi/templates/articles/article_create.html
{% extends 'base2.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {# <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li> #}
      <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">{% trans 'Articles' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Write a new article' %}</li>
    </ol>
  </nav>
  <form action="{% url 'articles:write_new' %}" enctype="multipart/form-data"  id="article-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save as draft' %}</button>
      <a href="{% url 'articles:list' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}

alemi/templates/articles/article_detail.html
{% extends 'base2.html' %}
{% load static i18n %}
{% load comments crispy_forms_tags thumbnail humanize %}

{% block title %}{{ article.title|title }}{% endblock %}

{% block content %}
  <!-- Page Content -->
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {# <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li> #}
        <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">{% trans 'Articles' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ article.title|title }}</li>
      </ol>
    </nav>
    <div class="row">
      <!-- Post Content Column -->
      <div class="col-lg-8">
        <!-- Title -->
        <h1 class="mt-4">{{ article.title|title }}</h1>
        <!-- Author -->
        <p class="lead">{% trans 'by' %}
          <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name|title }}</a>
        </p>
        <hr>
        <!-- Date/Time -->
        <p>{% trans 'Posted' %} {{ article.timestamp|naturaltime }}  </p>
        <hr>
        <!-- Featured Image -->
        {% thumbnail article.image "900x300" as im %}
          <img src="{{ im.url }}" alt="{% trans 'Featured Image' %}" class="card-img-top">
        {% empty %}
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="Card Image">
        {% endthumbnail %}
        <!-- <img src="{{ MEDIA_URL }}{{ article.image }}" lt="{% trans 'Featured Image' %}" class="card-img-top"> -->
        <hr>
        <!-- Post Content -->
        <p class="card-text">{{ article.get_markdown|safe }}</p>
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Leave a Comment' %}:</h5>
          <div class="card-body">
            {% if user.is_authenticated %}
              {% get_comment_form for article as form %}
              <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="next" value="{% url 'articles:article' article.slug %}" />
                <input type="submit" value="{% trans 'Add comment' %}" id="id_submit" />
              </form>
            {% endif %}
          </div>
        </div>

        <!-- Single Comment -->

        {% get_comment_list for article as comment_list %}
        {% for comment in comment_list %}
          <div class="media mb-4">
            {% thumbnail comment.user.picture "x50" as im %}
              <img class="d-flex mr-3 rounded-circle" src="{{ im.url }}" alt="{% trans 'Picture Profile' %}" id="pic" />
            {% empty %}
              <img class="d-flex mr-3 rounded-circle" src="{% static 'img/user.png' %}" height="50px" alt="{% trans 'No Profile Picture' %}" />
            {% endthumbnail %}
            <div class="media-body">
              <h5 class="mt-0">{{ comment.user.get_profile_name|title }}</h5>
              {{ comment }}
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Write Article Widget -->
        {% if request.user.is_authenticated %}
          <div class="card my-4">
            <div class="card-body text-center">
              <a class="btn btn-success" href="{% url 'articles:write_new' %}" title="{% trans 'Write a new article' %}"><i class="fa fa-pencil" aria-hidden="true"></i> {% trans 'New Article' %}</a>
              <a class="btn btn-primary" href="{% url 'articles:edit_article' article.id %}" title="{% trans 'Edit this article' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Edit' %}</a>
            </div>
          </div>
        {% endif %}
        <!-- Cloud Tag Widget -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Cloud tag' %}</h5>
          <div class="card-body">
            {% for tag in article.tags.all %}
              <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
{% endblock content %}

alemi/templates/articles/article_list.html
{% extends 'base2.html' %}
{% load static i18n %}
{% load humanize thumbnail %}

{% block title %} {% trans 'Articles' %} {% endblock %}

{% block head %}

{% endblock head %}

{% block content %}

  <!-- Page Content -->
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{% url 'articles:list' %}">{% trans 'Articles' %}</a></li>
      </ol>
    </nav>
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8">
        {% for article in articles %}
          <!-- Blog Post -->
          <div class="card mb-4">
            {% thumbnail article.image "750x300" as im %}
              <img src="{{ im.url }}" alt="{% trans 'Featured Image' %}" class="card-img-top">
            {% empty %}
              <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            {% endthumbnail %}
            <div class="card-body">
              <h2 class="card-title">{{ article.title|title }}</h2>
              <p class="card-text">{{ article.get_markdown|safe|truncatechars:150 }}</p>
              <a href="{% url 'articles:article' article.slug %}" class="btn btn-primary">{% trans 'Read More' %} &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              {% trans 'Posted' %} {{ article.timestamp|naturaltime }}
              <i class="lead fa fa-user"></i>
              <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name|title }}</a>
              {% for tag in article.tags.names %}
                <a href="#">{{ tag }}</a>
              {% endfor %}
            </div>
          </div>
        {% empty %}
          <h4 class="no-data">{% trans 'There is no published article yet' %}. <a href="{% url 'articles:write_new' %}">{% trans 'Be the first one to publish one' %}!</a></h4>
        {% endfor %}

        {% if is_paginated %}
          <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Newer' %}</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Older' %} &rarr;</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
            {% endif %}
          </ul>
        {% endif %}

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">
        <!-- Write Article Widget -->
        {% if request.user.is_authenticated %}
          <div class="card my-4">
            <div class="card-body text-center">
              <a class="btn btn-success" href="{% url 'articles:write_new' %}" title="{% trans 'Write a new article' %}"><i class="fa fa-pencil" aria-hidden="true"></i> {% trans 'New Article' %}</a>
              <a class="btn btn-primary" href="{% url 'articles:drafts' %}" title="{% trans 'Drafts' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Drafts' %}</a>
            </div>
          </div>
        {% endif %}
        <!-- Cloud Tag Widget -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Cloud tag' %}</h5>
          <div class="card-body">
            {% for tag, count in popular_tags %}
              <a href="#"><span class="badge badge-info">{{ count }} {{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

{% endblock content %}

alemi/templates/articles/article_update.html
{% extends 'base2.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {# <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Home' %}</a></li> #}
      <li class="breadcrumb-item"><a href="{% url 'articles:drafts' %}">{% trans 'Drafts' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Update an article' %}</li>
    </ol>
  </nav>
  <form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data"  id="article-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" class="btn btn-primary update">{% trans 'Update' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save as draft' %}</button>
      <a href="{% url 'articles:drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}